# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 16:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mac_address', models.CharField(max_length=100)),
                ('is_on', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=10)),
                ('intensity', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('number_of_devices', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='light',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lights',
                                    to='home_control.Room'),
        ),
    ]
