# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 17:01
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='date_update',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='room',
            name='info',
            field=models.CharField(default='No action', max_length=350),
        ),
        migrations.AlterField(
            model_name='light',
            name='color',
            field=models.CharField(max_length=15),
        ),
    ]
