# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='color',
            field=models.CharField(max_length=15),
        ),
    ]
