# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 09:03
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home_control', '0002_auto_20170426_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('is_on', models.BooleanField(default=False)),
                ('pin_code', models.CharField(max_length=10)),
                ('voice_activation', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks',
                                           to='home_control.Room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('is_on', models.BooleanField(default=False)),
                ('away_mode', models.BooleanField(default=False)),
                ('schedule', models.CharField(max_length=1000)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugs',
                                           to='home_control.Room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=100)),
                ('connection_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Thermostat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('is_on', models.BooleanField(default=False)),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermostats',
                                           to='home_control.Room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Webcam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('is_on', models.BooleanField(default=False)),
                ('night_vision', models.BooleanField(default=False)),
                ('motion_detection', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webcams',
                                           to='home_control.Room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
