# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home_control', '0005_auto_20170531_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='brand',
            field=models.CharField(default='Brand', max_length=50),
        ),
        migrations.AddField(
            model_name='lock',
            name='brand',
            field=models.CharField(default='Brand', max_length=50),
        ),
        migrations.AddField(
            model_name='plug',
            name='brand',
            field=models.CharField(default='Brand', max_length=50),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='brand',
            field=models.CharField(default='Brand', max_length=50),
        ),
        migrations.AddField(
            model_name='webcam',
            name='brand',
            field=models.CharField(default='Brand', max_length=50),
        ),
    ]
