# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home_control', '0006_auto_20170618_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_set', models.BooleanField(default=False)),
            ],
        ),
    ]
