# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 23:33
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home_control', '0007_homerule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homerule',
            old_name='name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='homerule',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
