# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home_control', '0009_auto_20170624_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='color',
            field=models.CharField(default='150 150 150', max_length=15),
        ),
        migrations.AlterField(
            model_name='plug',
            name='schedule',
            field=models.CharField(default='nothing', max_length=1000),
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='temperature',
            field=models.IntegerField(default=0),
        ),
    ]
